name: Integration tests

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
    paths:
      - 'packages/contracts/**'
      - 'packages/router/**'
  pull_request:
    branches:
      - main
    paths:
      - 'packages/contracts/**'
      - 'packages/router/**'
  workflow_dispatch:
    paths:
      - 'packages/contracts/**'
      - 'packages/router/**'

jobs:
  integration_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 21.1.0
        uses: actions/setup-node@v3
        with:
          node-version: 21.1.0
      - name: Build for testing
        run: |
          cd ./packages/contracts/
          yarn && yarn compile
          cd ../router
          yarn && yarn compile
          cd ../periphery
          yarn && yarn compile
      - name: Integration testing
        run: |
          cd ./packages/int-tests/
          yarn test
