name: Unit tests router
on:
  push:
    paths:
      - 'packages/router/**'
  pull_request:
    paths:
      - 'packages/router/**'
  workflow_dispatch:
    paths:
      - 'packages/router/**'
jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 24.2.0
        uses: actions/setup-node@v3
        with:
          node-version: 24.2.0
      - name: Build for testing router
        run: |
          cd packages/router
          yarn
          yarn test
