name: Unit tests contracts
on:
  push:
    paths:
      - 'contracts/**'
      - 'test/**'
  pull_request:
    paths:
      - 'contracts/**'
      - 'test/**'
  workflow_dispatch:
    paths:
      - 'contracts/**'
      - 'test/**'
jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 24.2.0
      uses: actions/setup-node@v3
      with:
        node-version: 24.2.0
    - name: Build for testing contracts
      run: |
        yarn && yarn compile
        yarn test
      env:
        ETH_NODE_URL: ${{ secrets.ETH_NODE_URL }}
        ARB_NODE_URL: ${{ secrets.ARB_NODE_URL }}
