name: Unit tests contracts
on:
  push:
    paths:
      - 'packages/contracts/**'
  pull_request:
    paths:
      - 'packages/contracts/**'
  workflow_dispatch:
    paths:
      - 'packages/contracts/**'
jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 24.2.0
      uses: actions/setup-node@v3
      with:
        node-version: 24.2.0
    - name: Build for testing contracts
      run: |
        cd packages/contracts
        yarn
        yarn test
