name: Unit tests periphery
on:
  push:
    paths:
      - 'packages/periphery/**'
  pull_request:
    paths:
      - 'packages/periphery/**'
  workflow_dispatch:
    paths:
      - 'packages/periphery/**'
jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 24.2.0
        uses: actions/setup-node@v3
        with:
          node-version: 24.2.0
      - name: Build for testing periphery
        run: |
          cd packages/contracts
          yarn
          yarn compile
          cd ../router
          yarn compile
          cd ../periphery
          yarn test
        env:
          ETH_NODE_URL: ${{ secrets.ETH_NODE_URL }}
          ARB_NODE_URL: ${{ secrets.ARB_NODE_URL }}
